### ISSUE TITLE
this error

### ISSUE THREAD

**Issue by dumojun101** [lucasduport/YoutubeGPT#2]
E:\2023\2023\02\20230227-周一\用ChatGPT总结内容\YoutubeGPT-main>python main.py https://youtu.be/AyOnug-3OKM sp
Traceback (most recent call last):
  File "E:\2023\2023\02\20230227-周一\用ChatGPT总结内容\YoutubeGPT-main\main.py", line 2, in <module>
    import youtube_api as yt
  File "E:\2023\2023\02\20230227-周一\用ChatGPT总结内容\YoutubeGPT-main\youtube_api.py", line 4, in <module>
    print(YouTubeTranscriptApi.__version__)
AttributeError: type object 'YouTubeTranscriptApi' has no attribute '__version__'

**Comment by lucasduport** [comment]
I will fix this in my next commit. Stay tuned, I did not updated the latest version.

**Comment by lucasduport** [comment]
The repo is now up to date, make sure you installed the requirements. And enjoy ! :)

**Comment by dumojun101** [comment]
thanks very much
